export const FETCH_ALL_PLACE = "FETCH_ALL_PLACE";
export const SET_CURRENT_PLACE = "SET_CURRENT_PLACE";
export const SET_HOVERED_CARD = "SET_HOVERED_CARD";

export const NEW_BOOKING = "NEW_BOOKING";
export const SET_GUEST_COUNT = "SET_GUEST_COUNT";

export const FETCH_HOST = "FETCH_HOST";
export const FETCH_RECOMMENDED_EXPERIENCE = "FETCH_RECOMMENDED_EXPERIENCE";
export const FETCH_FILTERED_EXPERIENCES = "FETCH_FILTERED_EXPERIENCE";
export const FETCH_ALL_EXPERIENCES = "FETCH_ALL_EXPERIENCES";
export const FETCH_LIMITED_EXPERIENCES = "FETCH_LIMITED_EXPERIENCES";
export const SET_CURRENT_EXPERIENCE = "SET_CURRENT_EXPERIENCE";

export const LOGIN_OAUTH2 = "LOGIN_OAUTH2";
export const REGISTER_STATUS = "REGISTER_STATUS";
export const SET_REGISTER_END = "SET_REGISTER_END";

export const SET_GEO_LOCATION = "SET_GEO_LOCATION";

export const SET_CURRENCY = "SET_CURRENCY";